### PR TITLE
[WIP] Split updatevars!() for Fourier transformed variables

### LINKED ISSUE #81: Separate updatevars! for physical space and Fourier space
Updating variables in physical space requires an inverse Fourier transform, which in turns requires a `deepcopy()`. Sometimes, though, we only need to update the Fourier transform of variables. Therefore if we split `updatevars!` into two separate function we might gain on allocation.

### PR DESCRIPTION
**Pull request by navidcy**
Closes #81

### CODE REVIEW

**Comment by navidcy** [comment]
@glwagner, I reckon you were thinking something like this, right?

**Review by glwagner — APPROVED** [review]
When was I thinking of something like this?

**Comment by navidcy** [comment]
haha, we were chatting about it over txt or call (I don't remember).

https://github.com/FourierFlows/GeophysicalFlows.jl/issues/81

**Comment by navidcy** [comment]
But now that I look closer it only makes sense for MultilayerQG and in particular for the fluxes diagnostics; I'l revise.

**Pull request closed without merging**
