### PR TITLE
Convert all animations in Docs from mp4 to gifs

### LINKED ISSUE #113: Animations in Docs don't show up in Safari

### PR DESCRIPTION
**Pull request by navidcy**
https://fourierflows.github.io/GeophysicalFlowsDocumentation/previews/PR157/

Closes #113

### CODE REVIEW

**Review by glwagner — APPROVED** [review]
Love gif's! I usually use fps=8 but if you have a lot of output it makes sense to speed it up...

**Comment by navidcy** [comment]
Do you reckon the animations go fast? They look good on my screen.

**Comment by navidcy** [comment]
(The only problem with gifs is that they are bigger in file size...)

**Comment by glwagner** [comment]
I think you could decrease the number of outputs and change to fps=8 to speed up the runs, that's all.

**Comment by glwagner** [comment]
Right, so decreasing the number of snapshots and also slowing the movies down to obtain a similar effect would also reduce the file size.

**Comment by navidcy** [comment]
Well, the numbers here are the minimum that my eyes and brain feel good with. E.g., examples with stochastic forcing become too flickery...

But if you wanna have a go trying to reduce the numbers go for it :)

**Comment by navidcy** [comment]
Damn... you got me started now :)

**Comment by glwagner** [comment]
I think it's ok if the movies don't look "continuous". The question is not "how pretty" but "how useful", I think.

**Comment by navidcy** [comment]
as pretty as one can get! :)

**Comment by navidcy** [comment]
I'll merge now and we can work on this at some later time. Until then I'll try to keep cleaning the GeophysicalFlowsDocumentation repo.

**Pull request merged**
