### PR TITLE
Fix a typo in contributing.md

### PR DESCRIPTION
**Pull request by szy21**

### CODE REVIEW

**Review by glwagner — APPROVED** [review]
<3

**Comment by navidcy** [comment]
@szy21 thanks! Try bringing your branch up to date with main. I added a quick and dirty fix for the issue with the symmetric colorbar limits which will make the Docs build go on OK.

**Review by navidcy — APPROVED** [review]

**Comment by szy21** [comment]
@navidcy Thanks! I just rebased the branch.

**Comment by navidcy** [comment]
there is something wrong with the buildkite cis at the moment, but the docs should build OK now!

**Comment by navidcy** [comment]
@szy21 can you merge? (not sure if you have the rights to do so... that's why I ask)

**Comment by szy21** [comment]
> @szy21 can you merge? (not sure if you have the rights to do so... that's why I ask)

No I couldn't find where to merge it, and that's why I haven't done it. I guess I don't have the permission?

**Pull request merged**
